Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from wpisy import views as v

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', v.glowna, name="glowna"),
    path('o_mnie/', v.o_mnie, name="o_mnie"),
    path('wpis/<str:pk>/', v.wpis, name="wpis"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('serce/', v.serce, name="serce"),
]

urlpatterns += [
    path('prehistoria/', v.prehistoria, name="prehistoria"),
    path('starożytność/', v.starożytność, name="starożytność"),
    path('średniowiecze/', v.średniowiecze, name="średniowiecze"),
    path('nowożytność/', v.nowożytność, name="nowożytność"),
    path('współczesność/', v.współczesność, name="współczesność"),
    path('mikrohistoria/', v.mikrohistoria, name="mikrohistoria"),
    path('biografistyka/', v.biografistyka, name="biografistyka"),
    path('drobne-newsy/', v.drobnenewsy, name="drobnenewsy"),
    path('raczek-nieboraczek/', v.raczeknieboraczek, name="raczeknieboraczek"),
    path('filozofia/', v.filozofia, name="filozofia"),
    path('literatura/', v.literatura, name="literatura"),
    path('refleksje/', v.refleksje, name="refleksje"),
    path('psychologia/', v.psychologia, name="psychologia"),
    path('polska/', v.polska, name="polska"),
    path('wynalazki-odkrycia-dzieła/', v.wynalazkiodkryciadzieła, name="wynalazkiodkryciadzieła"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wpisy/models.py
from django.db import models
from django.utils import timezone
import uuid
from ckeditor.fields import RichTextField

class Entry(models.Model):
    title = models.CharField(max_length=34)
    subtitle = models.CharField(max_length=156)
    thumbnail = models.ImageField(null=True, blank=True)
    description = RichTextField()
    source = models.TextField()
    tags = models.ManyToManyField('Tag', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    heart_count = models.IntegerField(default=0)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    shows = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    #podepnij PostgreSQL!

    @property
    def imageURL(self):
        try:
            img = self.thumbnail.url
        except:
            img = ''
        return img

class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'up'),
        ('down', 'down'),
    )

    user = models.CharField(max_length=24, default="Jasiek")
    single_entry = models.ForeignKey(Entry, on_delete=models.CASCADE, null=True, blank=True)
    body = models.TextField(null=True, blank=True,)
    value = models.CharField(max_length=50, choices=VOTE_TYPE,)
    update = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.user

class Tag(models.Model):
    name = models.CharField(max_length=200)
    thumbnail = models.ImageField(null=True, blank=True)
    description = models.CharField(max_length=280, default="Domyślny opis")
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    left_or_right = models.CharField(max_length=255, default="left")
    when = models.CharField(max_length=280, default="Poza czasem")

    def __str__(self):
        return self.name

class MainPicture(models.Model):
    content = models.CharField(max_length=200)
    thumbnail = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=200, default="Główny")

templates/glowna.html
{% extends "szablony/baza.html" %}

{% block title %} Ogrod {% endblock %}

{% block content %}
<h2>Najnowsze</h2>
<hr style="height: 2px; color: #009f94; opacity:unset">
<br><br>
<div class="row">
    <div class="col-sm-1 items">
    </div>
    <div class="col-sm-7 items">
        <div class="allEntrys">
            {% for x in article %}
                <div class="BoxEntry">
                    <a href="/wpis/{{x.id}}">
                        <div class="entry2" style="background-image:url({{ x.thumbnail.url }});">
                        </div>
                        <div class="title2">
                            {{ x.title }}
                            <br>
                            <span style="font-size: 0.6em; color: burlywood;">{{x.created}}</span>
                            <div class="subtitle" style="color: rgb(54, 54, 54); font-size: 15px; margin-top: 10px;">
                                {{ x.subtitle }}
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-sm-3 items">
        <div class="popular-post">
            
        </div>
    </div>
    <div class="col-sm-1 items">
    </div>
</div>
<hr style="height: 2px; color: #009f94; opacity:unset">
<div class="row">
    <div class="col-sm-12 items">
        {% for x in history %}
            <div class="entry" style="background-image:url({{ x.thumbnail.url }}); background-position: center; background-size: cover;">
                <a href="/wpis/{{x.id}}">
                    <div class="title">
                        {{ x.title }}
                        <div class="subtitle" style="color: rgb(54, 54, 54); font-size: 15px; margin-top: 10px;">
                            {{ x.subtitle }}
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
<hr style="height: 2px; color: #009f94; opacity:unset">

<div class="row">

</div>
    <!-- Swiper JS -->
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

    <!-- Initialize Swiper -->
    <script>
      var swiper = new Swiper(".mySwiper", {
        speed: 600,
        parallax: true,
        pagination: {
          el: ".swiper-pagination",
          clickable: true
        },
        navigation: {
          nextEl: ".swiper-button-next",
          prevEl: ".swiper-button-prev"
        }
      });
    </script>
<br>
{% endblock %}

templates/kategorie.html
{% extends 'szablony/baza_tag.html' %}

{% block content %}
    <div style="max-width: 100vh; background-color: floralwhite; margin-bottom: 200px; position: relative; top: -10vh; border-radius: 0.2em; box-shadow: 0 2px 10px rgb(0 0 0 / 85%);">
    <br>
    <form method="get">
        <input class="search__input" type="text" placeholder="Search">
            {{myFilter.form}}
        <button type="submit" class="btn btn-primary">Wyszukaj</button>
    </form>
        <div class="row example-split">
             <div class="col-xs-12 col-xs-offset-12 col-sm-12 col-sm-offset-12">
                <ul class="timeline timeline-split">
                {% for x in tags %}
                        <li class="timeline-item">
                            <div class="timeline-info">
                                <span style="color: grey;">{{x.created}}</span>
                            </div>
                            <div class="timeline-marker"></div>
                            <div class="timeline-content">
                                <a href="/wpis/{{x.id}}">
                                    <div class="category_box">
                                        
                                            <div class="content_category">
                                                <h3 class="timeline-title">{{x.title}}</h3>
                                                <hr style="background-color: tomato; width: 60%; margin: 0 auto;">
                                                <span class="HeartAndComment" style="color: tomato;">
                                                    <i class="fas fa-heart"></i>
                                                    <span class="ALLheart" style="font-family: 'Poiret One', cursive;">{{ x.heart_count }}</span>
                                                    <i class="fas fa-comments"></i>
                                                    <span style="font-family: 'Poiret One', cursive;">{{ x.review_set.count }}</span>
                                                    <i class="fas fa-eye"></i>
                                                    <span style="font-family: 'Poiret One', cursive;">{{x.shows}}</span>
                                                </span>
                                                <span class="description">{{x.subtitle}}</span>
                                            </div>
                                            <div class="category_image_up">
                                                <div class="category_image" style="background-image: url({{ x.thumbnail.url }})">
                                                    
                                                </div>
                                            </div>

                                    </div>
                                </a>
                            </div>
                        </li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
<!--https://codepen.io/brady_wright/pen/NNOvrW TIMELINE-->

templates/o_mnie.html
{% extends "szablony/baza.html" %}

{% block content %}

<span style="color=black;">Nazywam się Gracjan</span>
{% endblock %}

templates/pojedynczy_wpis.html
{% extends 'szablony/baza_wpis.html' %}

{% block content %}
    <!--background-image:url({{ articleObj.thumbnail.url }});-->
    <div style="max-width: 100vh; background-color: floralwhite; margin-bottom: 200px; position: relative; top: -10vh; border-radius: 0.2em; box-shadow: 0 2px 10px rgb(0 0 0 / 85%);">
        <p class="description">{{articleObj.description | safe}}</p>
        <br><br><br>
        <div class="heartDiv" style="display: table;">
            <h3 style="float:left; color: white;">Myślę, więc serduszkuję!</h3>
            <button type="button" class="heart animate__animated animate__pulse animate__infinite	infinite" data-toggle="tooltip" data-placement="top" title="Daj serducho!" style="float:left;">
                <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                </svg>
            </button>
        </div>
        <br><br><br>
        
        <div class="shares" style="display: table; margin: 0 auto;">
            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank">
                <button type="button" class="btn" data-toggle="tooltip" data-placement="top" title="Udostępnij na FB" style="padding: 7px 30px;color: #009e96;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                    </svg>
                </button>
            </a>
            <a href="https://twitter.com/home?status={{articleObj.title}}%20{{ request.build_absolute_uri }}" target="_blank" >
                <button type="button" class="btn" data-toggle="tooltip" data-placement="top" title="Udostępnij na TT" style="padding: 7px 30px;color: #009e96;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                        <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                    </svg>
                </button>
            </a>
            <button type="button" class="btn clipboard" data-toggle="tooltip" data-placement="top" title="Kopiuj link" style="padding: 7px 30px;">
                <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-link-45deg" viewBox="0 0 16 16" style="color: #009e96;">
                    <path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1.002 1.002 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4.018 4.018 0 0 1-.128-1.287z"/>
                    <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243L6.586 4.672z"/>
                </svg>
            </button>
        </div>
        <hr style="color: white;">
        <h3 style="color: white;">Recencje</h3>
        {% for review in reviews %}
            <p>{{review.body}}</p>
        {% endfor %}
    </div>
{% endblock %}